### ISSUE TITLE
Wii Rock Band 1 Drumset

### ISSUE THREAD

**Issue by miniTilK** [rbdrum2midi/rbdrum2midi#5] opened 2017-12-01 19:43 UTC
Hi,

First I want to congratulate you for this project. Thank to you, I was able to transform an old plastic game accessory into a electronic drum set for my children, and they love it. And it is working on arm cpu with very few dependencies.

I have a Wii RockBand 1 drumset, and i confirm what has been said previously:
I needed to change this line: 
*devh = libusb_open_device_with_vid_pid(NULL, 0x1bad, 0x3110); 
into
*devh = libusb_open_device_with_vid_pid(NULL, 0x1bad, 0x0005);

**Comment by jferiago** [comment] 2018-02-01 02:38
Hello miniTilK

I was able to detect my wii rockband 1 , but i got no sound...

i added my user to audio group but i need to run as root to detect...

did you were able to get sound?

Thanks

$ /usr/local/bin/rbdrum2midi  -rb1 -dbg
Could not find/open device, try running as root?
$ sudo /usr/local/bin/rbdrum2midi  -rb1 -dbg
claimed interface
Setting up alsa
client:port = 128:0
Returning 1
Debug Mode Enabled..
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
# Bass
10000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
# red
84000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
# yellow
88000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
# blue
81000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
# green
82000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=5

**Comment by miniTilK** [comment] 2018-02-01 08:10
Yes, i was able to have some sound as audio user.

May be the issue here is not about the right to access the audio, but the right to access the "joystick".

In my side, I created a udev rule like that :
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="0005", GROUP="audio", MODE="0664"

To be sure  that audio user has the right to access the drumset.

It is also indicated in the readme of rbdrum2midi:

> To fix usb permission problems create the file 90-drumkit.rules with the following line:
> 
> 
> SUBSYSTEM=="usb", ATTR{idVendor}=="12ba", ATTR{idProduct}=="0210", GROUP="audio", MODE="0664"
> SUBSYSTEM=="usb", ATTR{idVendor}=="12ba", ATTR{idProduct}=="0120", GROUP="audio", MODE="0664"
> SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="0003", GROUP="audio", MODE="0664"
> SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="0005", GROUP="audio", MODE="0664"

**Comment by randomas** [comment] 2018-02-01 15:46
Hi there and thank you for using our project!
Unfortunately I havn't handled the code in years and I have a bad memory ... ;-p

In order to use the code as non-root user you need to set the usb permissions as indicated. 

As far as sound goes, in order to get sound you need to route the midi signals generated by rbdrumtomidi to a midi drumkit. This is done in our case using qjackctl and hydrogen. The midi mapping is set up for the yamaha vintage kit in Hydrogen. 
 Hope this helps.

**Comment by ssj71** [comment] 2018-02-01 15:49
> I was able to detect my wii rockband 1 , but i got no sound...

Keep in mind this only outputs midi, so it doesn't generate any sound. Instead you must connect it to some sound generator like a sampler or synthesizer. Hydrogen, qsampler, or linux sampler are popular options.

Thanks for the feedback @miniTilK I haven't had much time to update the project. I think I've added the changes, but want to verify before I push: the drum mapping all works then?

@jferiago did your mapping not work? if you run it with -v and without the -dbg flag does it show the drum hits?

I'm wondering if maybe there are different wii rb1 kits?

**Comment by jferiago** [comment] 2018-02-03 05:31
miniTilK , randomnas , ssj71... thanks for your answer, I really appreciate it...


Here is what I do today...

- Installed a fresh ubuntu
- Disabled pulseaudio
- Installed jack and qjackctl
- Added the lines to 90-drumkit.rules 
- I was able to start  /usr/local/bin/rbdrum2midi  -v (was tested adding -rb1 parameter too, same result)
- started hydrogen
- started qjacktl and connected hydrogen to drumkit client

i got no sound

- jack is running fine, because i start "jack_simple_client" and i hear the beep when connect the program in qjackctl
- drumkit client appears on the settings menu of hydrogen
- I got response on the debug of rbdrum2midi

feria@tama:~$ /usr/local/bin/rbdrum2midi -v
claimed interface
Setting up alsa
client:port = 128:0
Returning 1
Rock Band drum kit detected.
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
84000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
88000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
81000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
82000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3
00000880 80808000 00000000 00000000 00000000 02000200 020002 kit type=3

Do I need to modify any config on hydrogen? i moved some parameters but i had no luck...

feria@tama:~$ lsusb  | grep Harm
Bus 001 Device 003: ID 1bad:0005 Harmonix Music 


Thanks in advance...

**Comment by randomas** [comment] 2018-02-03 12:01
Is hydrogen registering any hits? If it is, the issue is hydrogen not connected to Jack's audio out (improbable), otherwise there's an issue with the midi mapping. Iether the drumkit you're using in hydrogen is mapped weirdly (try Yamaha vintage kit) or your rb kit is one we've never seen and we need to write a mapping for it.

**Comment by jferiago** [comment] 2018-02-03 15:43
Hydrogen is connected to jack, because if I create a simple pattern on the GUI and press "play", or i click on "snare" or "hi hat" text,  i get sound...

I tried with yamaha vintage kit, same results

On Hydrogen:

Preferences-> Midi system
- Midi Driver: Alsa
- Input Game Drumkit port 2
- Channel: all

Debug -> audio engine info i have:
- Midi Input: AlsaMidiDriver
- Connected to: Game Drumkit port 2
(If I configure Jackmidi as a midi input and re-open same window, "Game Drumkit port 2" does not appears as an option to connect)

input mode -> tried both (instrument and drumkit)

Are there a way to debug if hydrogen is receiveing the signals from the drumkit?

Thanks!!

**Comment by randomas** [comment] 2018-02-03 18:39
In hydrogen open the mixer, if the hits are being received you see them in
real time.

Il 03 Feb 2018 4:43 PM, "jferiago" <notifications@github.com> ha scritto:

**Comment by ssj71** [comment] 2018-02-05 19:55
I haven't used hydrogen much, is it a midi channel issue? I think by default we send on channel 10 IIRC. Don't forget the -rb1 parameter in rbdrum2midi too.

**Comment by ssj71** [comment] 2018-12-06 20:51
I'm closing this as it seems the title issue is resolved. If you still have problems, please open a new issue for it. Thanks.

**Closed as completed by ssj71** 2018-12-06 20:51 UTC
